apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: express
  name: express
  namespace: mission-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: express
    spec:
      containers:
      - image: freemanpolys/mission-dev
        name: mission-dev
        resources: {}
status: {}
