apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: express
  name: express
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: express
  type: LoadBalancer
status:
  loadBalancer: {}
